groups:
  - name: datacreek.rules
    rules:
      - alert: EigshTimeoutStorm
        expr: increase(eigsh_timeouts_total[30m]) > 5
        for: 10m
      - alert: SVGPJitterStorm
        expr: rate(gp_jitter_restarts_total[10m]) > 0.01
        for: 10m
        labels:
          severity: warning
      - alert: RedisLowHitRatio
        expr: redis_hit_ratio < 0.3
        for: 5m
        labels:
          severity: warning
      - alert: EigshTimeoutCritical
        expr: increase(eigsh_timeouts_total[1h]) > 2
        for: 1m
        labels:
          severity: critical
