groups:
  - name: datacreek.rules
    rules:
      - record: redis_low_hit_ratio_threshold
        expr: 0.3
      - record: eigsh_timeout_storm_threshold
        expr: 5
      - record: eigsh_timeout_critical_threshold
        expr: 2
      - alert: EigshTimeoutStorm
        expr: increase(eigsh_timeouts_total[30m]) > eigsh_timeout_storm_threshold
        for: 10m
        labels:
          severity: warning
      - alert: SVGPJitterStorm
        expr: rate(gp_jitter_restarts_total[10m]) > 0.01
        for: 10m
        labels:
          severity: warning
      - alert: RedisLowHitRatio
        expr: redis_hit_ratio < redis_low_hit_ratio_threshold
        for: 5m
        labels:
          severity: warning
      - alert: EigshTimeoutCritical
        expr: increase(eigsh_timeouts_total[1h]) > eigsh_timeout_critical_threshold
        for: 1m
        labels:
          severity: critical
      - alert: CachePressure
        expr: ingest_queue_fill_ratio > 0.9 and redis_hit_ratio < redis_low_hit_ratio_threshold
        for: 5m
        labels:
          severity: critical
      - alert: GraphwaveP95Slow
        expr: p95_graphwave_ms > 250
        for: 10m
        labels:
          severity: warning
      - alert: IngestQueueHigh
        expr: ingest_queue_fill_ratio > 0.8
        for: 10m
        labels:
          severity: critical
